/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PortafolioRouteImport } from './routes/portafolio'
import { Route as NuestraHistoriaRouteImport } from './routes/nuestra-historia'
import { Route as IndexRouteImport } from './routes/index'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioRoute = PortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NuestraHistoriaRoute = NuestraHistoriaRouteImport.update({
  id: '/nuestra-historia',
  path: '/nuestra-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/portafolio': typeof PortafolioRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/portafolio': typeof PortafolioRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/portafolio': typeof PortafolioRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nuestra-historia' | '/portafolio' | '/servicios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nuestra-historia' | '/portafolio' | '/servicios'
  id: '__root__' | '/' | '/nuestra-historia' | '/portafolio' | '/servicios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NuestraHistoriaRoute: typeof NuestraHistoriaRoute
  PortafolioRoute: typeof PortafolioRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio': {
      id: '/portafolio'
      path: '/portafolio'
      fullPath: '/portafolio'
      preLoaderRoute: typeof PortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuestra-historia': {
      id: '/nuestra-historia'
      path: '/nuestra-historia'
      fullPath: '/nuestra-historia'
      preLoaderRoute: typeof NuestraHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NuestraHistoriaRoute: NuestraHistoriaRoute,
  PortafolioRoute: PortafolioRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
